// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgOlFM2d6Fl4Wdic03MrIQUi_8s35GzJU',
    appId: '1:952987709086:android:40260e23944d89e8ea158f',
    messagingSenderId: '952987709086',
    projectId: 'chat-app-e0b4d',
    storageBucket: 'chat-app-e0b4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-gADGeB0FYWyPForJI6p3dA5acdc7kAU',
    appId: '1:952987709086:ios:903ad058368dca1dea158f',
    messagingSenderId: '952987709086',
    projectId: 'chat-app-e0b4d',
    storageBucket: 'chat-app-e0b4d.appspot.com',
    iosClientId: '952987709086-vnie6g4b5a34f9n9lklmi52oacumr2t5.apps.googleusercontent.com',
    iosBundleId: 'com.example.testefirebase',
  );
}
